safe: true
lsi: false
google_analytics: G-ZE89C6CL4T
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge