safe: true
lsi: false
google_analytics: UA-59289414-1
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge